# Generated by Django 5.0.6 on 2024-05-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applibreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookcover',
            field=models.URLField(blank=True),
        ),
    ]
