# Generated by Django 5.0.3 on 2024-05-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applibreria', '0002_alter_book_bookcover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='menssenger',
            new_name='messege',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='address_location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_province',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
