# Generated by Django 5.0.3 on 2024-05-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applibreria', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
